version: "3.4"

services:
  db:
    container_name: "db"
    logging:
      driver: none
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root_db!
        - MONGO_INITDB_DATABASE=admin
    command: ["--auth", "--quiet", "--bind_ip_all"]
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - joya_db:/data/db

  api:
    container_name: "api"
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - COOKIE_SECRET=1PrYrTNFMXUvphPt9bJuzRC0UQ3yqj6Z
      - JWT_SECRET=WyILUzs614nroDOw5g7NezSfCqDWBgeU
      - API_PORT=5000
      - MONGO_URI=mongodb://admin:admin_pwd@db:27017/joya
    volumes:
      - ./api:/app
    ports:
      - 5000:5000

volumes:
  joya_db:
    driver: local
