class MainTextPalettes {
  static const Map<String, String> textFr = {
    "BIENVENUE": "BIENVENUE",
    "VOS_PLANTES": "Vos plantes connectées 🌱",
    "EMAIL_LABEL_DEFAULT_TEXTFIELD": "Adresse email",
    "NAME_LABEL_DEFAULT_TEXTFIELD": "Nom",
    "SURNAME_LABEL_DEFAULT_TEXTFIELD": "Prénom",
    "PASSWORD_LABEL_DEFAULT_TEXTFIELD": "Mot de passe",
    "CONFIRMATION_PASSWORD_LABEL_DEFAULT_TEXTFIELD":
        "Confirmation du mot de passe",
    "INSCRIPTION": "Inscription",
    "CONNEXION_BUTTON_DEFAULT_TEXTFIELD": "Connexion",
    "ABOUTDECO": "Déconnexion",
    "CONFIRMATIONMAIL_BUTTON_DEFAULT_TEXTFIELD": "Ouvrir Mail",
    "RECUPERTION_COMPTE_BUTTON_DEFAULT_TEXTFIELD": "Récupérer mon compte",
    "RECUP": "Mot de passe oublié ?",
    "DELETE_ACCOUNT": "Supprimer mon compte",
    "REGARDEBOITE": "Regarde ta boîte mail !",
    "TEXTSENDEMAIL":
        "Pour confirmer ton adresse mail, ouvre le mail que tu as reçu et clique sur le lien !",
    "TEXT CONFIRM MAIL QUESTION": "As-tu déjà un compte ?",
    "QUESTION EMAIL": "Connecte toi",
    "OPENMAIL": "Ouvrir Mail",
    "NOPLANT": "Aucune plante ajoutée.",
    "ADDFIRSTPLANT":
        "Ajoutez votre première plante en appuyant sur le bouton de scanner.",
    "MY_PLANT": "Mes Plantes",
    "NAME_PLANT": "Nom de ma plante",
    "PLANT_TYPE": "Nom scientifique de ma plante",
    "CONFIG_NETWORK": "Configurer mon réseau",
    "CONFIG_PLANT": "Configurer mon capteur",
    "MY_NETWORK": "Nom du réseau",
    "LOCALISATION_PLANT": "Localisation de ma plante",
    "CONNECT_PLANT": "Connecter ma plante",
    "SCAN_QRCODE": "Scannez le QR code de votre capteur.",
    "SEARCH": "Rechercher",
    "ABOUT_MY_ACCOUNT": "Mon compte",
    "ABOUT": "JOYA & Moi",
    "ABOUTPRENIUM": "Devenir membre premium",
    "ABOUTNOTIF": "Notifications",
    "ABOUT_HELP": "FAQ / Aide",
    "ABOUT_JOYA": "À propos",
    "ABOUT_SETTING": "Paramètre d'application",
    "PLUSINFO": "Plus d’informations",
    "CONDITIONURL": "Condition d’utilisation & confidentialité.",
    "SUIVANT": "Suivant",
    "VALIDER": "Valider",
    "VIDE": "",
    "BUILD": "Site en cours de construction",
    "ERROR_EMAIL": "Veuillez saisir une adresse email valide",
    "ERROR_PASSWORD": "Veuillez saisir un mot de passe valide",
  };
}
